### ISSUE TITLE
No module named 'cloudComPy'

### ISSUE THREAD

**Issue by devspacetimelu** [CloudCompare/CloudComPy#102]
Hello, 
I am new CloudCompare and python, I succeeded in getting all the files in the right place and setting up the environment.

envCloudComP.bat gives
Checking environment, Python test: import cloudComPy
Environment OK!

and ctest also passes all the checks.

But when I try to import cloudComPy in python after activating the environment, it gives the no module found error.
How can I solve this problem?

Thank you,
Rohith

**Comment by prascle** [comment]
Hello,

That's strange, the message "Environment OK!" means that  envCloudComPy.bat is  able to import successfully CloudComPy, and ctest calls python scripts that import CloudComPy...

The following should be working, from the conda prompt:
```
conda activate CloudComPy310
cd <path install>\CloudComPy310
envCloudComPy.bat
python
```
Then, on the Python prompt:
`import cloudComPy as cc
`

If this does not work can you state precisely your sequence of instructions and the result ?

Regards,
Paul

**Comment by prascle** [comment]
Hi,
If you are using spyder, please have a look on issue #80, it may solve your problem.

best,
Paul

**Comment by prascle** [comment]
Hi, Test 42 may fail if the memory is not released immediately,  I guess it depends on the environment Python is running in. It's not a problem.
Test 50 uses a huge data file (see issue #100), which is not downloaded automatically, so the test is skipped if the file is not present.
Paul

**Comment by jerrychoices** [comment]
> Hi, For some reason I could not get the environment working on Spyder, but it works on Visual Studio Code. I finally have some time to get started with this again.
> 
> Thank you, Rohith

guys！I wanna know how you run cloudcompy in vscode with miniconda, i just counter this problem.

**Comment by thomasTUK** [comment]
Me too

**Comment by Waydelucien** [comment]
> > Hi, For some reason I could not get the environment working on Spyder, but it works on Visual Studio Code. I finally have some time to get started with this again.
> > Thank you, Rohith
> 
> guys！I wanna know how you run cloudcompy in vscode with miniconda, i just counter this problem.

Have you ever solved this problem? I am using vscode as well and I encouter the same problem...

**Comment by prascle** [comment]
On Windows (the same as in Linux) I launch visual studio code in the CloudComPy environment, with the command `code `in the conda prompt:


```
(base) C:\Users\paulr>conda activate CloudComPy310

(CloudComPy310) C:\Users\paulr>cd CloudComPy\install\CloudComPy310

(CloudComPy310) C:\Users\paulr\CloudComPy\install\CloudComPy310>envCloudComPy.bat
Checking environment, Python test: import cloudComPy
Environment OK!

(CloudComPy310) C:\Users\paulr\CloudComPy\install\CloudComPy310>code

(CloudComPy310) C:\Users\paulr\CloudComPy\install\CloudComPy310>
```

In VScode, you have to select the Python interpreter from conda CloudComPy310 environment.

Paul
