### ISSUE TITLE
Problems starting CloudComPy on Amazon EC2 Linux

### ISSUE THREAD

**Issue by kxd195** [CloudCompare/CloudComPy#107]
I'm trying to get CloudComPy running on Amazon EC2 Linux and here's what happens when I run: 
`. ~/CloudComPy310/bin/condaConfig.sh activate CloudComPy310` after following all of the Linux install instructions:

```
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.
```

Any help would be appreciated!

**Comment by prascle** [comment]
Hi, I think this is the same issue as #105 
Paul

**Comment by kxd195** [comment]
No solution as current CloudCompare requires a GUI of some sort as you've identified in #105 

A workaround I did was install a Ubuntu OS on EC2, and also VNCServer as referenced here: https://ubuntu.com/tutorials/ubuntu-desktop-aws#3-configuring-the-vnc-server

After that, you can Remote Desktop/VNC into the instance and run CloudComPy from the GUI terminal. That does work.
