### ISSUE TITLE
SF cell statistics with Rasterize in cloudComPy

### ISSUE THREAD

**Issue by bthetford** [CloudCompare/CloudComPy#109]
Hello,

I noticed that in CloudCompare 2.13, the Rasterize function now includes scalar field statistics, where you can choose any percentile you want. Is there any way to achieve this using cloudComPy?

I'm trying to compute a roughness scalar field, and then take percentiles of roughness for each cell in a given grid. 

Thanks,
Beau

**Comment by prascle** [comment]
Hello,

CloudComPy is probably not up to date with the latest developments of the Rasterize function, I will check what is missing and try to add it.

Regards,
Paul

**Comment by bthetford** [comment]
Thank you!! I was able to write my own workaround following [this article.](https://towardsdatascience.com/how-to-automate-lidar-point-cloud-processing-with-python-a027454a536c)

But, it's probably not as fast as what you'll implement!

beau
