### ISSUE TITLE
ComputeVolume25D on two ASCII clouds (approx 6.3MB) causing SIGKILL9 on Linux

### ISSUE THREAD

**Issue by kxd195** [CloudCompare/CloudComPy#110]
Wondering if anyone's experiencing an issue running CloudComPy's ComputeVolume25D method against two clouds, where the process is killed with code 9 on Linux.

I'm using two ASCII clouds, each with approx 6.3MB file size. My machine has 16GB memory + 16GB swap, so I believe it's more than enough memory to handle this process, yet it is killed each time this command runs.

**Comment by prascle** [comment]
Hello,
Can you provide sample files to reproduce the problem ? 

Paul

**Comment by kxd195** [comment]
@prascle  Sure, what's your email? I'd prefer to send it directly to you than posted online. Thanks!

**Comment by prascle** [comment]
@kxd195 Fine, please use development@openfields.fr . I just added this public email on my profile.

Regards,
Paul

**Comment by prascle** [comment]
Hello, 
I checked your data. 
You need to define a gridStep corresponding to your clouds: in your case, the distance between the points is about 2.5, so a gridStep of 1.0 is sufficient. With a smaller gridStep, you use more memory and CPU for nothing (if you keep 0.05, you will use at least 400 times the memory needed!)
Your data have huge coordinate values and they are automatically shifted. In your case, the offset is the same for both clouds, but you should control this (see https://www.simulation.openfields.fr/documentation/CloudComPy/html/userLoad.html#getting-the-shift-value).
```
import cloudComPy as cc
cloud1 = cc.loadPointCloud("cloud1.xyz")
cloud2 = cc.loadPointCloud("cloud2.xyz")
print(cloud1.getGlobalShift())
print(cloud2.getGlobalShift())
report = cc.ReportInfoVol()
isOk = cc.ComputeVolume25D(report, ground=cloud1, ceil=cloud2, vertDim=2, gridStep=1.0, groundHeight=0, ceilHeight=0)
print(report.volume)
```
Regards,
Paul
