### ISSUE TITLE
Install CloudComPy "the specified file was not found"

### ISSUE THREAD

**Issue by Myraun** [CloudCompare/CloudComPy#113]
Hello ! I'm trying to install CloudComPy with conda. I use the Anaconda Prompt, but I have a problem.

After creating and configuring a new environment for CloudComPy, I use the command "cd <path install>/CloudComPy310" but an error is displayed: "the specified file was not found" :

![image](https://github.com/CloudCompare/CloudComPy/assets/134513928/02e62d76-bd17-44d4-b3a5-bb3c86381721)

However, I did download the CloudComPy file, "CloudComPy310_20230511.7z", which is in the folders of my computer.
How should I do to be able to use CloudComPy?

Thank you

(And sorry for my approximate english.)

**Comment by prascle** [comment]
Oh, `CloudComPy310_20230511.7z` is an archive (a kind of zip file): on Windows, you need a tool like [7-zip](https://www.7-zip.org/download.html) to extract the content somewhere on your computer.
Then replace `<path install>` with the path where you  extracted `CloudComPy310_20230511.7z`.
Paul

**Comment by Myraun** [comment]
It's finally works ! Thank you
