### ISSUE TITLE
ComputeVolume25D: parameters (Empty Cell, Max Edge Length, Grid Cell Height)

### ISSUE THREAD

**Issue by jlee-67** [CloudCompare/CloudComPy#125]
Hi Paul,

Thanks for developing CloudComPy. This has been super useful for my project. 

In my project, I'm trying to compute 2.5D Volume (using Empty Cells: interpolate, Max edge length value = 5, Grid Cell Height = average height). I noticed that [cloudComPy.ComputeVolume25D](https://www.simulation.openfields.fr/documentation/CloudComPy/html/cloudComPy.html#cloudComPy.ComputeVolume25D) does not have the max edge length, empty cells, and cell height (min/avg/max) parameters that I can use. Has this been implemented in CloudComPy? 

Other functions like cloudComPy.ExtractSlicesAndContours has parameter (maxEdgeLength: float = 0) and cloudComPy.RasterizeTo_____has (EmptyCellFillOption, emptyCellFillStrategy) so I was just wondering if I missed something for ComputeVolume25D.

If this hasn't been implemented, could this be added in the next update?

Thank you.

**Comment by prascle** [comment]
Hi,
These parameters have not been implemented for `ComputeVolume25D`, I add that to my TODO list!

Paul

**Comment by jlee-67** [comment]
> Hi,
> 
> These parameters have not been implemented for `ComputeVolume25D`, I add that to my TODO list!
> 
> 
> 
> Paul

Hi Paul, 

Thanks for your quick reply. That would be great since I think those parameters pretty important when performing volume calculation. I really appreciate your help and I look forward to the next update! 

Thanks.

**Comment by jlee-67** [comment]
Hi @prascle , 

I have a quick question. Will the update include all of these options for Empty Cell Parameters? (similiar to this [cloudComPy.EmptyCellFillOption](https://www.simulation.openfields.fr/documentation/CloudComPy/html/cloudComPy.html#cloudComPy.EmptyCellFillOption)) 

Thank you very much.

LEAVE_EMPTY

FILL_MINIMUM_HEIGHT

FILL_MAXIMUM_HEIGHT

FILL_CUSTOM_HEIGHT

FILL_AVERAGE_HEIGHT

INTERPOLATE_DELAUNAY

**Comment by prascle** [comment]
Hi,
That's the idea!
Paul

**Comment by jlee-67** [comment]
> Hi,
> 
> That's the idea!
> 
> Paul

Great! Thank you again.

**Comment by jlee-67** [comment]
Hello Paul,

I just saw this update! Thank you for updating this feature. Are those parameters working now? If so, should I try it out by editing the source files in my local machine? 

Thank you!

**Comment by jlee-67** [comment]
Got it. I will wait for the next update this week!

Thank you Paul.

**Comment by jlee-67** [comment]
Hi Paul,

Just saw new release with this issue resolved. I will this close issue once I test out the new update / version of the 2.5 tool!.

Thanks!
