### ISSUE TITLE
Are there any API to unload loaded point cloud data

### ISSUE THREAD

**Issue by Cova8bitdots** [CloudCompare/CloudComPy#126]
I am working on a program to determine the size of the Boundary Box of a point cloud when combined from several files, each divided into dozens, without actually combining them. Although I sequentially read files within a for loop and perform calculations, the memory usage increases each time a file is read. I have tried using del on variables loaded with CloudComPy.loadPointCloud() and also used gc.collect(), but the issue persists. Is there an UnloadAPI available to release the memory of the files loaded using the API?

**Comment by prascle** [comment]
Hi, 
I think the [deleteEntity function](https://www.simulation.openfields.fr/documentation/CloudComPy/html/cloudComPy.html#cloudComPy.deleteEntity) is what you need.
see the corresponding [use case](https://www.simulation.openfields.fr/documentation/CloudComPy/html/userUseCases.html#avoid-memory-leaks-in-an-iterative-process).

Regards,
Paul

**Comment by Cova8bitdots** [comment]
@prascle 
Thank you for your quick response.
The problem has been solved!!

I don't have to allocate more than 70GB memory any more :)
