### ISSUE TITLE
CloudComPy Installation

### ISSUE THREAD

**Issue by matti-christmann** [CloudCompare/CloudComPy#136]
Hello,

I am having troubles installing CloudComPy and do not know how to continue from here. I am using anaconda navigator to create the new environment, but it is not possible for me to install the required packages. My error message reads the following:
`
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package qt-5.15.4-h2d74725_0 is excluded by strict repo priority
  - package boost-1.74.0-py39hefe7e4c_5 is excluded by strict repo priority
  - package gdal-3.5.3-py39hed9c3b8_24 is excluded by strict repo priority
  - package scipy-1.8.1-py39hfbf2dce_3 is excluded by strict repo priority
  - package pcl-1.12.0-h68e0818_0 requires boost-cpp >=1.74.0,<1.74.1.0a0, but none of the providers can be installed
  - package pdal-2.4.0-h299ffe6_1 requires libgdal >=3.4.2,<3.5.0a0, but none of the providers can be installed
  - package openmp-8.0.1-0 requires llvm-openmp 8.0.1 h1ad3211_0, but none of the providers can be installed
  - package cgal-5.4-py310hf5e1058_0 requires cgal-cpp 5.4.*, but none of the providers can be installed
  - package mysql-8.0.22-h57928b3_3 requires mysql-server 8.0.22 h4a6d357_3, but none of the providers can be installed
  - package opencv-4.5.4-py310hadfdc90_1 requires numpy 1.21.*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ boost 1.74**  is not installable because it conflicts with any installable versions previously reported;
├─ cgal 5.4**  is installable with the potential options
│  ├─ cgal 5.4 would require
│  │  └─ cgal-cpp 5.4.* , which requires
│  │     └─ mpfr >=4.1.0,<5.0a0 , which conflicts with any installable versions previously reported;
│  ├─ cgal 5.4 would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ cgal 5.4 would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  └─ cgal 5.4 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
├─ gdal 3.5**  is not installable because it conflicts with any installable versions previously reported;
├─ mysql 8.0**  is not installable because there are no viable options
│  ├─ mysql [8.0.19|8.0.20] would require
│  │  └─ mysql-server [8.0.19 hf4dd9fb_0|8.0.20 hf4dd9fb_0], which requires
│  │     └─ icu >=64.2,<65.0a0 , which conflicts with any installable versions previously reported;
│  ├─ mysql [8.0.20|8.0.21|8.0.22] would require
│  │  └─ mysql-server [8.0.20 hfac38c1_1|8.0.21 h56d97c4_0|8.0.21 h576c1c4_2|8.0.21 hba8823c_1|8.0.22 h576c1c4_0], which requires
│  │     └─ icu >=67.1,<68.0a0 , which conflicts with any installable versions previously reported;
│  ├─ mysql [8.0.22|8.0.23|...|8.0.27] would require
│  │  └─ mysql-server [8.0.22 h4a6d357_3|8.0.22 h99750b9_1|...|8.0.27 h2b15538_0], which requires
│  │     └─ libevent >=2.1.10,<2.1.11.0a0 , which conflicts with any installable versions previously reported;
│  ├─ mysql [8.0.27|8.0.28] would require
│  │  └─ mysql-server [8.0.27 h186548d_1|8.0.27 h77165ef_2|...|8.0.28 h77165ef_2], which requires
│  │     └─ icu >=69.1,<70.0a0 , which conflicts with any installable versions previously reported;
│  ├─ mysql [8.0.28|8.0.29|8.0.30|8.0.31|8.0.32] would require
│  │  └─ mysql-server [8.0.28 h0065552_4|8.0.28 h0fe0749_3|...|8.0.32 hd6e9830_0], which requires
│  │     └─ icu >=70.1,<71.0a0 , which conflicts with any installable versions previously reported;
│  ├─ mysql 8.0.32 would require
│  │  └─ openssl >=3.1.0,<4.0a0 , which conflicts with any installable versions previously reported;
│  ├─ mysql [8.0.32|8.0.33] would require
│  │  └─ openssl >=3.1.1,<4.0a0 , which conflicts with any installable versions previously reported;
│  ├─ mysql 8.0.33 would require
│  │  └─ openssl >=3.1.2,<4.0a0 , which conflicts with any installable versions previously reported;
│  └─ mysql 8.0.33 would require
│     └─ openssl >=3.1.3,<4.0a0 , which conflicts with any installable versions previously reported;
├─ numpy 1.22**  is installable with the potential options
│  ├─ numpy [1.21.2|1.21.5|1.22.3] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ numpy [1.21.2|1.21.5|1.22.3] would require
│  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  ├─ numpy [1.22.0|1.22.1|1.22.2|1.22.3|1.22.4], which can be installed;
│  └─ numpy 1.22.3 would require
│     └─ python >=3.11,<3.12.0a0 , which can be installed;
├─ opencv 4.5**  is installable with the potential options
│  ├─ opencv [4.5.4|4.5.5] would require
│  │  └─ numpy 1.21.*  with the potential options
│  │     ├─ numpy [1.21.0|1.21.1|...|1.21.6] conflicts with any installable versions previously reported;
│  │     ├─ numpy [1.21.2|1.21.5] would require
│  │     │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  │     ├─ numpy [1.21.2|1.21.5|1.22.3], which can be installed (as previously explained);
│  │     └─ numpy [1.21.2|1.21.5|1.22.3], which can be installed (as previously explained);
│  ├─ opencv [4.5.4|4.5.5] would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ opencv [4.5.4|4.5.5] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ opencv [4.5.4|4.5.5] would require
│  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  └─ opencv [4.5.0|4.5.1|4.5.2|4.5.3|4.5.5] conflicts with any installable versions previously reported;
├─ openmp 8.0**  is not installable because there are no viable options
│  ├─ openmp 8.0.0 would require
│  │  └─ llvm-openmp 8.0.0 h1ad3211_0, which conflicts with any installable versions previously reported;
│  ├─ openmp 8.0.0 would require
│  │  └─ llvm-openmp 8.0.0 h1ad3211_1, which conflicts with any installable versions previously reported;
│  └─ openmp 8.0.1 would require
│     └─ llvm-openmp 8.0.1 h1ad3211_0, which conflicts with any installable versions previously reported;
├─ pcl 1.12**  is not installable because there are no viable options
│  ├─ pcl [1.12.0|1.12.1] would require
│  │  └─ boost-cpp >=1.74.0,<1.74.1.0a0 , which conflicts with any installable versions previously reported;
│  └─ pcl 1.12.1 would require
│     └─ vs2015_runtime >=14.29.30139 , which conflicts with any installable versions previously reported;
├─ pdal 2.4**  is not installable because there are no viable options
│  ├─ pdal 2.4.0 would require
│  │  └─ libgdal >=3.4.2,<3.5.0a0 , which conflicts with any installable versions previously reported;
│  └─ pdal [2.4.0|2.4.1|2.4.2|2.4.3] would require
│     └─ geotiff >=1.7.1,<1.8.0a0 , which conflicts with any installable versions previously reported;
├─ pin-1 is not installable because it requires
│  └─ python 3.10.* , which conflicts with any installable versions previously reported;
├─ qt 5.15.4**  is not installable because it conflicts with any installable versions previously reported;
└─ scipy 1.8**  is not installable because it conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.10.* (labeled as 'pin-1')`

Please note, I've also installed LibMamba, as the ordinary process from anaconda was taking really long.

Any help would be greatly appreciated!
Matti

**Comment by prascle** [comment]
Hello Matti,
I didn't know LibMamba, I'll give it a try... 
Yes, the solver step with anaconda can be very time consuming, but you have to do it once, updates afterwards are faster.
I checked the time needed to recreate CloudComPy310 from scratch, on my laptop, under Windows, with miniconda3 (it should be the same with anaconda, and/or on Linux....)

- First step: update conda: 30 seconds
- Second step: create Python3.10 environment: 90 seconds (including deleting existing environment)
- third step: install all packages: 12 minutes (< 9 minutes for solver step, 3mn for installation)

Have you tried without LibMamba?
Note: During the resolution process, there may be a confusing message (_unsuccessful initial attempt using frozen solve_):
```
(base) C:\Users\paulr>conda activate CloudComPy310b

(CloudComPy310b) C:\Users\paulr>conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top

(CloudComPy310b) C:\Users\paulr>conda config --set channel_priority strict

(CloudComPy310b) C:\Users\paulr>conda install "boost=1.74" "cgal=5.4" cmake draco ffmpeg "gdal=3.5" jupyterlab laszip "matplotlib=3.5" "mysql=8.0" "numpy=1.22" "opencv=4.5" "openmp=8.0" "pcl=1.12" "pdal=2.4" "psutil=5.9" pybind11 "qhull=2020.2" "qt=5.15.4" "scipy=1.8" sphinx_rtd_theme spyder tbb tbb-devel "xerces-c=3.2"
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done
....

```
If it still doesn't work, could you please give more details about your configuration (Windows, Linux, first installation of conda or already used with other environments...).

Regards,
Paul

**Comment by matti-christmann** [comment]
Hi Paul,

Thanks for your response! From your message I got the idea of trying with fresh install miniconda3 aswell, and it worked!
It seems, that when creating a new environment from the anaconda navigator, it does not allow for all packages to be downgraded properly. With miniconda it seems to work, as some packages are freshly installed.

With LibMamba the whole process took me 11min.

Thanks again,
Matti
