### ISSUE TITLE
WindowsCondaBinary / CondaSSLError: OpenSSL

### ISSUE THREAD

**Issue by antoinebio** [CloudCompare/CloudComPy#139]
Hello
I wanted to work with the last package
so I started from scratch the installation with anaconda

I've got that kind of error

<img width="578" alt="image" src="https://github.com/CloudCompare/CloudComPy/assets/30265851/04fad301-f01d-4f59-9732-83206816f23f">

is it safe to bypass that error ? should we add that package ? 

https://anaconda.org/anaconda/openssl

I tried without any success. the issue is the same...

**Comment by antoinebio** [comment]
test on windows11. but this is not related to OS I guess

**Comment by prascle** [comment]
Hello,
I've encountered this problem once before, but I couldn't find any trace of it in my notes or in CloudComPy issues. I did some research and found this [link](https://github.com/conda/conda/issues/11982#issuecomment-1285538983).
I remember it was a success. I suppose this solution (copying conda dlls already installed somewhere in the conda path) is harmless. 
Maybe you can try it. I'll also try reinstalling miniconda from scratch, but that assumes you don't have many environments already installed...

**Comment by antoinebio** [comment]
Hello Paul
I was thinking that i could be possible I install manually the required package in my env.
like the one found here https://github.com/CloudCompare/CloudComPy/blob/33526956bce633eea49211196beb4fb76f46597e/building/conda-list_Windows10_310

But I think the best would be to start from scractch with a clean miniconda; i reckon sometime things are not going well with anaconda or miniconda.
will try with miniconda

**Comment by prascle** [comment]
Hello Antoine,
Before starting from scratch, you can try the solution given by [link ](https://github.com/conda/conda/issues/11982#issuecomment-1285538983). It's very quick to test.
I don't think installing the ssl package manually is enough...

**Comment by antoinebio** [comment]
work well with @prascle tips > updating DLL of conda then the package are well installed.

<img width="563" alt="image" src="https://github.com/CloudCompare/CloudComPy/assets/30265851/6c8c3aea-6648-4750-85be-c00d812ffbf3">
