### ISSUE TITLE
The account of the main CloudComPy developer and his contributions are not visible: sorry for the delay in answering questions.

### ISSUE THREAD

**Issue by rasclep** [CloudCompare/CloudComPy#164]
The [prascle](https://github.com/prascle/) account has been flagged for more than one month and it is no more visible, nor are the contributions on issues. The reinstatement request has not yet received a response from GitHub. Without knowing if and when this will be fixed, I'm going to try answering the questions from a new account, and I've cloned my working repository on [GitLab](https://gitlab.com/openfields1/CloudComPy), where it's also possible to post new issues. 
Sorry for the inconvenience,
Regards,
Paul

**Comment by prascle** [comment]
The reinstatetement is OK, problem solved. The GitLab repository will be kept as a clone, in case of new problem...
