### ISSUE TITLE
Option to save transformation matrices from ICP

### ISSUE THREAD

**Issue by mcgregorian1** [CloudCompare/CloudComPy#166]
In the command line version of [CloudCompare](https://www.cloudcompare.org/doc/wiki/index.php/Command_line_mode), the ICP function states

```
the corresponding transformation matrix is automatically saved in a separate text file (always).
```

It doesn't seem like this is an option in CloudComPy, nor is there a separate function that would do this. Can this functionality please be added to the ICP function? Or separately, is there another way to access the matrix as an output text file?

Thanks!

**Comment by prascle** [comment]
Hi,
The transformation matrix is given in the result structure in return of ICP function: see the [use case](https://www.simulation.openfields.fr/documentation/CloudComPy/html/userUseCases.html#cloud-registration-with-the-cloudcompare-implementation-of-icp-algorithm) and the [reference](https://www.simulation.openfields.fr/documentation/CloudComPy/html/cloudComPy.html#cloudComPy.ICPres). 
The [transformation matrix](https://www.simulation.openfields.fr/documentation/CloudComPy/html/ccPrimitives.html#cloudComPy.ccGLMatrix) object has several methods to get the parameters, including a `toString` method.

Best regards,
Paul

**Comment by mcgregorian1** [comment]
Ah, you're right, sorry about that. I had seen it before and I didn't catch that. Thanks!
