### ISSUE TITLE
Import Module cloudComPy

### ISSUE THREAD

**Issue by Group5AAU** [CloudCompare/CloudComPy#168]
Hello,
We are trying to use the cloudComPy module, but it is not working for us. Whenever we try to import the module cloudComPy, it gives the error 'ModuleNotFoundError: No module named 'cloudComPy'. We have installed the programme as per the installation folder, but with no luck. 
![nomodule](https://github.com/CloudCompare/CloudComPy/assets/169348458/857a9c79-bb3a-4fd7-909f-9df24c4be691)

When trying to import directly in the prompt, it gives the following:
QFileSystemWatcher: Removable drive notification will not work if there is no QCoreApplication instance.
JsonRPCPlugin::JsonRPCPlugin

Can anyone help? :-)

**Comment by prascle** [comment]
Hello, 
I assume you have followed the [instructions](https://github.com/CloudCompare/CloudComPy/blob/master/doc/UseWindowsCondaBinary.md). It looks like you've already installed the Conda environment but haven't activated it.
You need to use the Conda prompt terminal supplied with Conda and, in this terminal: 
```
conda activate CloudComPy310
cd <install path>\CloudComPy310
envCloudComPy.bat
```

`<path install>` is the directory where you unpacked the CloudComPy binary from [Windows CloudComPy binaries](https://www.simulation.openfields.fr/index.php/cloudcompy-downloads/3-cloudcompy-binaries/5-windows-cloudcompy-binaries).

If this doesn't work, please tell me which steps in the instructions are unclear or wrong.

Best regards,
Paul

**Comment by Group5AAU** [comment]
Hello again,
Thanks for the fast answer! As far as we're concerned, every step in the instructions have been followed (and re-done multiple times). The Conda environment is installed and activated, but when trying to 'import cloudComPy as cc' it says there is no module called 'cloudComPy'.

![image](https://github.com/CloudCompare/CloudComPy/assets/169348458/6811c526-bd5b-42a3-a9f9-fed443fb971c)

Everything seems to be working up until this point, but we can't seem to troubleshoot where it goes wrong? We are using the latest binary package.

Best regards!

**Comment by prascle** [comment]
Hello, 
After
```
conda activate CloudComPy310
cd c:\Users\ander\cloudComPy310
```
you must run
`envCloudComPy.bat
`
This shell script sets the environment required for CloudComPy and checks if the cloudComPy import works. This step is mandatory, before using CloudComPy.

Best regards,
Paul

**Comment by Group5AAU** [comment]
Hello,
We managed to solve the problem! Thank you very much for the help Paul!

Best Regards
