### ISSUE TITLE
envCloudComPy bat file not running

### ISSUE THREAD

**Issue by mansinnikam** [CloudCompare/CloudComPy#181]
Hello, I followed the instructions for installation of CloudComPy Wrapper on Windows using Conda
<img width="793" alt="Issue" src="https://github.com/user-attachments/assets/f9494cc6-2ca8-4efa-9860-5527a74241a0">
. I downloaded the bat file and extracted it in my CloudComPy310 environment folder and unzipped other files provided in binary as well. But I am getting this error. Can you help please?

**Comment by prascle** [comment]
Hello,
If you activate the CloudComPy environment you had to create in conda with `conda activate CloudComPy310`, your prompt should change from `(base)` to `(CloudComPy310)`: after that, envCloudComPy.bat should work.

I don't understand your last sentence: you need to create the CloudComPy310 environment, and unpack the Windows binary of CloudComPy elsewhere. **You must use envCloudComPy.bat from this extraction without moving it.** 

Best regards,
Paul

**Comment by mansinnikam** [comment]
Hey, so i did that but this is still coming. What should i do about this?
<img width="765" alt="Capture" src="https://github.com/user-attachments/assets/4170a678-c6a3-4a5c-b011-a42e5738ebb9">

**Comment by prascle** [comment]
Hmm, strange... 
Have you downloaded the latest Windows binary from [my site](https://www.simulation.openfields.fr/index.php/cloudcompy-downloads/3-cloudcompy-binaries/5-windows-cloudcompy-binaries)?
Could you check your conda CloudComPy310 environment?
In the anaconda prompt, `conda activate CloudComPy310` then `conda list` and compare the result with https://github.com/CloudCompare/CloudComPy/blob/master/building/conda-list_Windows11_310.
Your package list may be slightly different, but you should at least find all the packages in the command used to create the environment:
```
conda activate CloudComPy310
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install “ boost=1.74 ‘ ’ cgal=5.4 ‘ cmake draco ffmpeg ’ gdal=3.5 ‘ jupyterlab laszip ’ matplotlib=3.5 ‘ ’ mysql=8.0 ‘ ’ numpy=1.22 ‘ ’ opencv=4.5 ‘ ’ openmp=8. 0 “ ‘pcl=1.12’ ‘pdal=2.4’ ‘psutil=5.9’ pybind11 quaternion ‘qhull=2020.2’ ‘qt=5.15.4’ ‘scipy=1.8’ sphinx_rtd_theme spyder tbb tbb-devel ”xerces-c=3.2 ”
```
If you haven't found an obvious difference, you can perhaps give the result of the `conda list` command

**Comment by mansinnikam** [comment]
Is it needed for Pythonpath and Cloudcompy to be in same directory?

**Comment by prascle** [comment]
I am not sure to understand your question.
One of the purposes of envCloudComPy.bat is to add the CloudCompare directory (in the binary package) to the PythonPath.
The CloudCompare directory contains the cloudComPy Python module.
envCloudComPy.bat sets also the path required to find all the libraries (*.dll) used by the Python module.
If you use the CloudComPy Windows binary as it is, without any modification, and call the envCloudComPy.bat inside (after setting the conda CloudComPy310 environment), the PythonPath and Path should be correct.
