### ISSUE TITLE
Report generation in cloudcompare

### ISSUE THREAD

**Issue by Kuntal491** [CloudCompare/CloudComPy#187]
I have been using cloud compare and facing this issue. That it is no option for report generation neither i found any relevant resources regarding that. I want to generate the report in pdf format. I have use 2 aligned point cloud/ mesh and computed the distance. (deviation analysis) . I can easily do it in cloudcompare and get results in histogram and heat map of the object. But i have no option to export that in pdf . Like pdf should contain the heat map of the object and histogram. How this can be done ? . Please let me know if there are plugins or python scipt available for that.

Any suggestion/advice on this topic is very much help for me. 

Thank You.

**Comment by prascle** [comment]
Hello,
I'd like to know more about the content you'd like to include in your pdf report. For example, it's possible to generate histograms on image files (png, bmp, jpg, tif...) using CloudCompare's graphical interface or a CloudComPy Python script. The same thing can be done with raster functions on scalar fields. 

- I suppose it's possible to find Python tools to automatically generate a pdf report to your specifications, including these images and text. 
- Is there anything you can do in CloudCompare but not with CloudComPy?

Best regards,
Paul

**Comment by Kuntal491** [comment]
Hello @prascle ,
I have been looking for those python tools but have not found any yet which generated report directly. Report consists of images of the object , result of histogram, (standard deviation or variance etc. ).  I am trying so that in one click i get report. for example . I have already aligned 2 object .  and using cloudcomPy  (one line code )i am able to save the  c2m distance file. and it working fine. now i need report(pdf) of that saved_distance file. Like histogram and image of the object where deviation has occured more. or image of object from different angles. But i have not found any resources that do that. Is there way that i run a script or code and pdf is automatically downlaod. Is there a way for that. Beacuse most of other software have option to export as pdf. But in cloud compare i could not find any way. 

Thank You in advance. 

Regard,
Kuntal

**Comment by prascle** [comment]
Hello @Kuntal491,
There are several packages available for generating a PDF from a Python script. For example, [fpdf2](https://py-pdf.github.io/fpdf2/) allows you to mix text and images, enabling you to create a report to your own specifications. 
You'll need to install fpdf2 in your conda CloudComPy310 environment: `conda install fpdf2`.

Best regards,
Paul

**Comment by Kuntal491** [comment]
Hello @prascle ,

Thanks for that. I am able to build pdf .Problem is i need to automate it  . I have 2 mesh files . I can perform the distance or deviation analysis in software and i can visulize the heat map with scale and also the histogram of point cloud distances. But my question is can i automate that so that. user loads 2 mesh files and directtly this deviation anlysis is performed and saved in pdf (automatic). 

How to do that in code that it give output histogram and heat map of the image with scale in cloudcompy. How to get this things. I can build pdf if i have images. Right now i have opening application and then exproting results as imges. i need to automate . This is my question. Not manually. 

Thank you so much for your response.

Regrads,
Kuntal

**Comment by prascle** [comment]
Hello @Kuntal491 ,
I'm not sure I understand your question. I assume that if you want to automate your process, it's either because you want to apply it to hundreds of datasets, or because you want to provide a tool for people who aren't proficient in Python.
It looks like you've already found the Python instructions for all the basic steps in your process, from loading the mesh files to exporting the results to image files. 
You'll need to define the steps for grouping image files and any automatic comments into a PDF file. This part can be done with a few lines of Python using fpdf2. If you group all these Python instructions in a function taking your dataset as argument, you get your automatic procedure. That's the beauty of Python! What am I missing?

Regards,
Paul

**Comment by Kuntal491** [comment]
Hello @prascle ,
Lets assume i want to  give cloud compare to some user who does not know coding or python or not proficient in computers. Now i want that if users loads the mesh files and compare them(user loads them and compute the distance). He can see the results in cloud compare. But there is no option in cloud compare for exporting results to pdf directly. I need some automatic way or some functionality of that sort. Users clicks on that button and pdf is generated and saved , which contains the results. I am trying this. 

Results are heatmap of componeent with scale(images from different angles) and histogram 

Thank you so much 
Best Regards, 
Kuntal
