### ISSUE TITLE
Issue with installation on windows for version 2.13.2 (2024-09)

### ISSUE THREAD

**Issue by mcgregorian1** [CloudCompare/CloudComPy#197]
## Issue
I tried downloading and installing CloudComPy following the instructions, but the cloudComPy module can't be found when running `envCloudComPy.bat`. 

## What I have done to solve the problem
I ensured I followed the installation steps [here](https://gitlab.com/openfields1/CloudComPy/-/blob/master/doc/UseWindowsCondaBinary.md), including the activation and addition of packages. I installed it the same way on another computer and got the same error. I've also checked some of the other issues; this is similar to Issue #181 but the author of that issue did not put what solved the problem. I figured I'd open a new issue because it's with a newer version.

## Error messages
When I activate the environment and try to use it, the import cloudComPy attempt fails. Note that I get the path to the conda environment programmatically because this script is used by different computers at different work sites. In this case, my `condaPath` variable is `C:\Users\mcgregori\.conda\envs\CloudComPy310`.

```
@echo off
:: Step 1. Get the conda env path for CloudComPy
for /f "usebackq tokens=1,2" %%a in (`conda info --envs ^| findstr /c:"CloudComPy"`) do @set condaPath=%%b
echo This is the envpath: %condaPath%

:: Step 2. Activate the conda environment
call activate %condaPath%

:: Step 3. Check the env is correct and the paths are set
call CloudComPy310\envCloudComPy.bat

:: do script here

call conda deactivate
```

I've found that whether I run the contents of the `.bat` file above, or whether I manually run the following, I get the same error (below). I have a feeling I'm missing something simple, but do you have a recommendation for how to fix this?
```
conda activate C:\Users\mcgregori\.conda\envs\CloudComPy310
python
import cloudComPy as cc
```

Error
```
Checking environment, Python test: import cloudComPy
The environment seems to be incorrect! You need to set the conda environment for cloudComPy before runnfor cloudComPy before running this script!
"Incorrect Environment! Problem with Python test!"
```

**Comment by prascle** [comment]
Hello, 
Unfortunately, some time after releasing the latest version, I found that the list of packages I give [here](https://gitlab.com/openfields1/CloudComPy/-/blob/master/doc/UseWindowsCondaBinary.md) for the conda CloudComPy310 environment is not precise enough and that many package versions should be specified (conda packages are always being updated and what works once may be incorrect a few days later). 
When you download the version [here](https://www.simulation.openfields.fr/index.php/cloudcompy-downloads/3-cloudcompy-binaries/5-windows-cloudcompy-binaries/113-cloudcompy310-20240927), the instructions given on the download page are up to date. If you haven't already done so, please recreate the environment with:
```
conda activate
conda update -y -n base -c defaults conda

conda create -y --name CloudComPy310 python=3.10
   # --- erase previous env with the same name if existing

conda activate CloudComPy310
conda config --add channels conda-forge
conda config --set channel_priority flexible
conda install -y "boost=1.84" "cgal=5.6" cmake "draco=1.5" "ffmpeg=6.1" "gdal=3.8" jupyterlab laszip "matplotlib=3.9" "mpir=3.0" "mysql=8" notebook numpy "opencv=4.8" "openmp=8.0" "openssl=3.1" "pcl=1.14" "pdal=2.6" "psutil=6.0" pybind11 quaternion "qhull=2020.2" "qt=5.15.8" scipy sphinx_rtd_theme spyder tbb tbb-devel "xerces-c=3.2"
```
I hope this solves your problem.
Best regards,
Paul

**Comment by mcgregorian1** [comment]
Hi Paul,

Ah I see, that makes sense! I can confirm that when creating the environment again with those packages you listed, the environment test is passed.

However, I now have an instance where when I run the `.bat` file contents as above, I get no error.

But when I do the following code manually, it says there is no module named `cloudComPy`. Do you have an idea why this would be happening even though I'm accessing the same conda environment?
```
conda activate C:\Users\mcgregori\.conda\envs\CloudComPy310
python
import cloudComPy as cc

>>> import cloudComPy as cc
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cloudComPy'
```

**Comment by prascle** [comment]
Hi Ian,
envCloudComPy.bat is mandatory, it is needed to add cloudComPy in the Python path.
So :
```
(base) C:\Users\paulr>Conda activate CloudComPy310

(CloudComPy310) C:\Users\paulr>CloudComPy\install\CloudComPy310_20240927\CloudComPy310\envCloudComPy.bat
Checking environment, Python test: import cloudComPy
Environment OK!

(CloudComPy310) C:\Users\paulr>python
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:01:37) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudComPy as cc
QFileSystemWatcher: Removable drive notification will not work if there is no QCoreApplication instance.
JsonRPCPlugin::JsonRPCPlugin
>>>
```
Best regards,
Paul

**Comment by mcgregorian1** [comment]
Ahh right, got it. My bad, thank you!
