### ISSUE TITLE
Functionality to Load Entities?

### ISSUE THREAD

**Issue by xiangtaoxu** [CloudCompare/CloudComPy#31]
@prascle. Hi Paul. Is there any plan to have an IO functionality to enable reading multiple point clouds from a same entity .bin file?

Currently, I am using RANSAC to generate hundreds of small point clouds and I find writing/reading these files is becoming a throttle for the performance of my little program...

**Comment by prascle** [comment]
I think  [cc.importFile](https://www.simulation.openfields.fr/documentation/CloudComPy/html/cloudComPy.html?highlight=entities#cloudComPy.importFile) can do the job. 
Let me know if there are any problems with a large number of point clouds.
Paul

**Comment by xiangtaoxu** [comment]
Hi, Paul. Sorry that I forgot to reply. Thanks so much!

One related question is that my lidar scan files were saved in ptx, which has scanner position information. In CloudCompare GUI, I can get their center position by checking the Edit->Sensors->Edit. Is there a way to read the information in CloudComPy?

**Comment by xiangtaoxu** [comment]
Never mind, found a way to export the scanner information as an ASC II file. So should be straightforward!
