### ISSUE TITLE
issue using CloudComPy39 within Spyder | no issue with anaconda

### ISSUE THREAD

**Issue by antoinebio** [CloudCompare/CloudComPy#37]
Hello,
the package CloudComPy39 is running fine in anaconda prompt.

but if I want to use the Syder  IDE [Spyder] in that environment

![image](https://user-images.githubusercontent.com/30265851/163227213-e6918e8c-de4b-46e0-a0ce-f0c542538fe5.png)

then I've got an issue with qt pluging.

![image](https://user-images.githubusercontent.com/30265851/163226888-ad9a354b-4fe2-4436-bbdc-573ce0a9ea8a.png)

i tried to force reinstallation of both package below

![image](https://user-images.githubusercontent.com/30265851/163255354-340e481d-db67-4bbd-9bb5-c0a6fe95d64d.png)

![image](https://user-images.githubusercontent.com/30265851/163227720-3ad2efda-3d14-4569-a929-5c2b74b5b420.png)

still, SPYDER returns a issue when I execute my python code. this is not the case with anaconda prompt....

**Comment by prascle** [comment]
Hello,
I'm sorry but I'm confused by your first screenshot. I only tested Spyder by running the Spyder command in the Anaconda Prompt console:
![image](https://user-images.githubusercontent.com/63641539/163396025-7a51db8f-59da-4693-8a00-5d042f69dfab.png)
So I don't know if this way works for you.
You have a Spyder installation accessible through menus that I don't have (I didn't try to make these menus), and I don't know if the environment in which Spyder is launched is the same as the one in the Anaconda prompt console.

Paul

**Comment by antoinebio** [comment]
hello Paul
actually this is what i tested

![image](https://user-images.githubusercontent.com/30265851/163437206-5fa33b57-997b-4a0d-a985-1384cd429784.png)

then in spyder I run my script (that same script runs well in anaconda prompt)
but here I have got an issue with qt in SPYDER console

![image](https://user-images.githubusercontent.com/30265851/163437373-dcaef0e5-57f8-489f-8611-cfa75e56b6c4.png)

**Comment by prascle** [comment]
I can reproduce your problem when I remove `QT_PLUGIN_PATH` from the environment.
The script `envCloudComPy.bat` sets this variable.
Could you check this in the environment you use to launch spyder?
`echo %QT_PLUGIN_PATH%`
you should get something like:
`C:\Users\paulr\CloudComPy\install\CloudComPy39\\qtplugins`
(with the path of your install)

Paul

**Comment by antoinebio** [comment]
Hello Paul
this is what i've got

![image](https://user-images.githubusercontent.com/30265851/163569662-23b85217-a551-4556-9abb-9fb29eb02c20.png)

**Comment by antoinebio** [comment]
here it is
![image](https://user-images.githubusercontent.com/30265851/163571295-2d4625f3-ce34-4ecc-9f86-905339f86228.png)

sorry for the silly question
