### ISSUE TITLE
Slice mesh with 2d polygon

### ISSUE THREAD

**Issue by letatanu** [CloudCompare/CloudComPy#38]
Thank you for the useful wrapper. 
I'm working on slicing the mesh with 2d footprint. I could find a function in the point cloud called crop2d which is exactly what I want, but it is unavailable in mesh. My purpose is to slice the mesh as well as its texture. Can you help me with that? Thank you.

**Comment by prascle** [comment]
Hello,
The function to cut a mesh by a polyline is not yet available in CloudComPy. I looked at how to wrap in Python the CloudCompare function that does this.
There are several C++ functions that need to be adapted to allow this wrapping. 
I'm adding this to my todo list and will try to integrate it into my next version of CloudComPy (probably in 2-3 weeks) barring any unforeseen difficulties.

Regards,
Paul

**Comment by User2323321** [comment]
Hi, is there any news about the inclusion of this function? I need it badly!

**Comment by prascle** [comment]
Hello, 
the Crop2D mesh function is available in the new binaries [here](https://www.simulation.openfields.fr/index.php/download-binaries).

Paul

**Comment by letatanu** [comment]
Thank you so much for your effort. I will try it. I can close this topic as the function is already implemented.
