### ISSUE TITLE
Potential memory leak when running in a loop

### ISSUE THREAD

**Issue by daanbl** [CloudCompare/CloudComPy#40]
Hello,

I'm running the M3C2 algorithm in a loop on a large number of point cloud files, using the following code:

```
tile_tqdm = tqdm(all_tiles, unit='tile', smoothing=0)

for tile in tile_tqdm:
    [...]
    
    cloud1 = cc.loadPointCloud(path1, cc.CC_SHIFT_MODE.NO_GLOBAL_SHIFT)
    cloud2 = cc.loadPointCloud(path2, cc.CC_SHIFT_MODE.NO_GLOBAL_SHIFT)

    m3c2_cloud = cc.M3C2.computeM3C2([cloud1, cloud2], param_file)

    if m3c2_cloud is None:
        continue

    cc.SavePointCloud(m3c2_cloud, path_m3c2)
```

On every iteration of this loop, the RAM usage goes up by approximately 10MB (the size of the two input clouds varies but is usually around 0.5 MB, and the resulting M3C2 cloud is around 1.5MB. Only restarting the kernel frees up the RAM.

Any idea what is going on?

**Comment by prascle** [comment]
Hello,

This is an interesting problem!
CloudCompare wrapping in Python is quite simple, and does not handle Python garbage collector: in other words, when a Python object that wraps a C++ object in CloudCompare is destroyed, the C++ object is not impacted. (Similarly, if a C++ object in CloudCompare is destroyed, the Python object that represents it is not destroyed, although it is unusable).
In your example, the Python objects `cloud1, cloud2, m3c2_cloud` are automatically destroyed on the Python side at each loop turn, but not the created C++ CloudCompare entities.
This should be explicitly done with the `cloudComPy.deleteEntity` statement at the end of each iteration.

I hope this is enough and that it is correct: I admit that I have not spent much time testing these destruction operations in iterative configurations. I'll plan to add some more tests of this kind, to have some examples.

If you try this explicit destruction and see problems, let me know.
Regards,

Paul

**Comment by kbratsy** [comment]
> Merhaba
> 
> Bu ilginç bir sorun! Python'da CloudCompare sarmalaması oldukça basittir ve Python çöp toplayıcısını işlemez: başka bir deyişle, CloudCompare içinde bir C++ nesnesini sarmalayan bir Python nesnesi yok edildiğinde, C++ nesnesi etkilenmez. (Benzer şekilde, CloudCompare içindeki bir C++ nesnesi yok edilirse, onu temsil eden Python nesnesi kullanılamaz olmasına rağmen yok edilmez). Örneğinizde, Python nesneleri her döngü dönüşünde Python tarafında otomatik olarak yok edilir, ancak oluşturulan C++ CloudCompare varlıkları yok edilmez. Bu, her yinelemenin sonundaki ifadeyle açıkça yapılmalıdır.`cloud1, cloud2, m3c2_cloud``cloudComPy.deleteEntity`
> 
> Umarım bu yeterlidir ve doğrudur: Bu imha işlemlerini yinelemeli yapılandırmalarda test etmek için fazla zaman harcamadığımı itiraf ediyorum. Bazı örnekler vermek için bu tür testler eklemeyi planlayacağım.
> 
> Bu açık yıkımı denerseniz ve sorunlar görürseniz, bana bildirin. Saygılar
> 
> Paul

Thank you. I found a good solution to the problem I encountered.
