### ISSUE TITLE
Small maxSearchDist leads to failure in C2C distance computation

### ISSUE THREAD

**Issue by xiangtaoxu** [CloudCompare/CloudComPy#41]
Hi,

I find that when maxSearchDist is set to be small, there is a chance of failure when calling C2C distance calculation. When I did the computation in CloudCompare GUI, it failed as well. Do you know what is causing the problem?

I am attaching the two clouds I used to reproduce the problem.
[maxSearchDist_error.zip](https://github.com/CloudCompare/CloudComPy/files/8614077/maxSearchDist_error.zip)

**Comment by xiangtaoxu** [comment]
When I set the maxSearchDist to 0.18, the computation failed

**Comment by prascle** [comment]
Hello,

I am reproducing this behavior, but it seems normal to me.
See the CloudCompare wiki on [distance calculation](https://www.cloudcompare.org/doc/wiki/index.php/Distances_Computation).

The minimum distance between the two clouds is about 0.38.
The `computeApproxCloud2CloudDistance` function allows to have estimates of the min and max distance.
It seems to me that it does not make much sense to do the calculation with a maximum distance parameter lower than the estimated minimum.

Does this answer your question, or is there something I didn't understand?
Paul

**Comment by xiangtaoxu** [comment]
Thanks so much! It makes sense to me.

Now in my workflow, I do not call computeCloud2CloudDistance if the minimum of `Approx. distances` is larger than maxSearchDist. In this way, my program does not crash and saves ~1/3 of the time even considering I am only using single-thread with applying for a maxSearchDist in this scenario (previously I was using 15 threads without maxSearchDist)
