### ISSUE TITLE
Scalar Field Gradient and Statistics?

### ISSUE THREAD

**Issue by xiangtaoxu** [CloudCompare/CloudComPy#46]
Hi, is there any plan to add Scalar fields\Gradient functionality?

https://www.cloudcompare.org/doc/wiki/index.php/Scalar_fields%5CGradient

In general, it would be great if there is neighborhood statistics for scalar fields (which I guess is not so different from the current neighborhood geometric statistics functions?)

**Comment by prascle** [comment]
Hi, 
I'm adding the Scalar fields\Gradient functionality to my TODO list!
Do you have in mind some particular functions for the neighborhood statistics for scalar fields? 
Paul

**Comment by xiangtaoxu** [comment]
I think some basic descriptive statistics would be very helpful already, - mean, variance, median/percentile, gradient. For example, I am interested in the variability of point density within a neighborhood (variance of KNN within a radius), which might help to identify boundaries of objects.

If I think of anything, I will add them to this issue. Thanks so much!

**Comment by prascle** [comment]
Hi,
The new version [here](https://www.simulation.openfields.fr/index.php/download-binaries) gives access to the scalar field gradient.
I have done nothing more yet, there are already several functions available, I suppose you can compute a variability of point density with that, and I am not sure of what to add.
On clouds, you have all the functions corresponding to the CloudCompare menu `tools/other/geometric features` (see test024.py):
```
cc.computeApproxLocalDensity(...)
cc.computeCurvature(...)
cc.computeFeature(...)
cc.computeLocalDensity(...)
cc.computeMomentOrder1(...)
cc.computeRoughness(...)
```
On scalarFields you have the basic:
```
computeMeanAndVariance
computeMinAndMax, getMin, getMax
```

after, you have access to a lot of statistics via numpy (percentile, median, histogram...).
Paul

**Comment by xiangtaoxu** [comment]
Thanks so much!
