### ISSUE TITLE
Get TSL info

### ISSUE THREAD

**Issue by Masrhalsp** [CloudCompare/CloudComPy#57]
Hi, 
I have issue by getting the translation matrix or the location of scanner. This property is saved as child number zero but it is not possible to get information about it.
Thank you

**Comment by prascle** [comment]
Hi,
Could you provide a small data file example or tell me where to download some representative dataset ? 
Thanks and regards, 
Paul

**Comment by Masrhalsp** [comment]
Thank you for respond,
Actually I need to get translation vector or transformation matrix of the data.
The folowing data has multiple entity and each one has transformation matrix.
https://master.dl.sourceforge.net/project/e57-3d-imgfmt/E57Example-data/manitouNoInvalidPoints.e57?viasf=1

**Comment by prascle** [comment]
Thank you for this link, I was looking for such a file. I think it is clear for me now. I have found the relevant C++ code to wrap in Python And I am trying to define the best way to do this wrapping. 
Regards,
Paul

**Comment by Masrhalsp** [comment]
Thank you
