### ISSUE TITLE
Keep E57 structure.

### ISSUE THREAD

**Issue by natecdr** [CloudCompare/CloudComPy#58]
Hello,

I would like to import structured .e57 files, do some treatment on them and then save them as new .e57 files while keeping their structured nature. All of this through CloudComPy only.
I think CloudCompare GUI offers that option, but I was only able to export unstructured files from CloudComPy.
Do you have an idea of how that could be done, if it's even possible ?

Regards

**Comment by prascle** [comment]
Hello,

Could you provide an example of such a file ? It will help me to test and solve the problem.

Thanks and regards, 
Paul

**Comment by prascle** [comment]
When loading and saving the file with CloudCompare GUI, some parts of the structure seem not to be saved, and I see that the version of libE57 we use is much older than the version used to generate the example (tested on Linux)
Using CloudComPy to do the same thing, the file saved by CloudComPy gives a structure very similar to the file saved by the CloudCompare GUI, but the structure is not accessible from CloudComPy.
Providing access to this structure requires development, I will analyze the feasibility of this.
I will also check if there is something to improve using a newer version of libE57...

Paul

**Comment by natecdr** [comment]
Yes, access to the structure would be useful too.

Thanks !
