### ISSUE TITLE
cannot getPoint()

### ISSUE THREAD

**Issue by JavaZeroo** [CloudCompare/CloudComPy#68]
```
Traceback (most recent call last):
  File "/home/lijb/Code/pcd_regist_cc/main.py", line 23, in <module>
    main()
  File "/home/lijb/Code/pcd_regist_cc/main.py", line 17, in main
    print(up.getPoint())
Boost.Python.ArgumentError: Python argument types in
    PointCloudTpl_ccGenericPointCloud_QString.getPoint(ccPointCloud)
did not match C++ signature:
[1.zip](https://github.com/CloudCompare/CloudComPy/files/9449977/1.zip)

    getPoint(CCCoreLib::PointCloudTpl<ccGenericPointCloud, QString> {lvalue}, unsigned int)
```

I have upload my pcd
[1.zip](https://github.com/CloudCompare/CloudComPy/files/9449979/1.zip)

**Comment by JavaZeroo** [comment]
In addition, When I import CloudComPy, It said
```
QSocketNotifier: Can only be used with threads started with QThread
/home/paul/projets/CloudComPy/CloudComPy/CloudCompare/libs/qCC_db/src/ccLog.cpp [53] : trace OFF
/home/paul/projets/CloudComPy/CloudComPy/CloudCompare/libs/qCC_db/src/ccLog.cpp [53] : trace OFF
JsonRPCPlugin::JsonRPCPlugin
```

**Comment by prascle** [comment]
Hello,
The function getPoint requires the index of the point as an argument.
The following script works for me with your data:
```
import os
import sys
import math
import cloudComPy as cc
cloud=cc.loadPointCloud("1.pcd")
cloud.getPoint(0)
# (3.546738386154175, 6.642450332641602, 1.3494415283203125)
```
The messages  QSocketNotifier, trace and JsonRPCPlugin are notmal.

Regards
Paul

**Comment by JavaZeroo** [comment]
> Hello, The function getPoint requires the index of the point as an argument. The following script works for me with your data:
> 
> ```
> import os
> import sys
> import math
> import cloudComPy as cc
> cloud=cc.loadPointCloud("1.pcd")
> cloud.getPoint(0)
> # (3.546738386154175, 6.642450332641602, 1.3494415283203125)
> ```
> 
> The messages QSocketNotifier, trace and JsonRPCPlugin are notmal.
> 
> Regards Paul

thx bro, I think if it could conver all points to open3d or numpy it will be better☺️

**Comment by prascle** [comment]
Hello, 
There is a function to get all the points as a numpy array: see the [documentation](https://www.simulation.openfields.fr/documentation/CloudComPy/html/userNumpy.html) ☺️.
Paul
