### ISSUE TITLE
Turn off tracing in the newest linux binary?

### ISSUE THREAD

**Issue by xiangtaoxu** [CloudCompare/CloudComPy#76]
Hi,

I recently upgraded to the newest linux binary with python 3.10. However, I find that tracing information such as below always show up no matter whether I change the environmental variable or not.

/home/paul/projets/CloudComPy/CloudComPy/pybind11/cloudComPy.cpp [61] : modulePath: /home/xu-eeb/Utils/CloudComPy310/lib/cloudcompare/cloudComPy/__init__.py

/home/paul/projets/CloudComPy/CloudComPy/pyAPI/pyCC.cpp [829] : pyCCComputeGeomCharacteristic

What could I do to mute these tracing?

Thanks!

**Comment by prascle** [comment]
Hi, 
I reproduce this problem, I don't have a solution yet (without rebuilding CloudComPy). I think I introduced a bug in the initialization of traces when switching to pyBind11. I will fix this with the next version.
Regards,
Paul

**Comment by xiangtaoxu** [comment]
Hi, Paul

I am trying the newest release but I got a error saying that GLIBC 2.32 not found. Just to confirm, the newest version needs 2.32? The instructions still say 2.29 or higher.

**Comment by prascle** [comment]
Oh, I made a mistake in my build process! I'm gradually migrating from Ubuntu 20.04 to Ubuntu 22.04, and building and testing with both systems. Unfortunately, I uploaded the Ubuntu 22.04 binary, which requires at least glibc 2.32...
I intend to provide binaries built on Ubuntu 20.04 as long as possible, these binaries work with newer Linux.
I will fix this in the next release.
Paul
