### ISSUE TITLE
pyccTrace.h file missing?

### ISSUE THREAD

**Issue by proprogramerX** [CloudCompare/CloudComPy#84]
Hi im currently facing this issue while trying to run `make -j12 && make test && make install` for CloudComPy on Ubuntu 20.04.
I'm missing pyccTrace.h files? I'm uncertain as to what is the root cause of this problem.

![Screenshot from 2023-01-11 10-04-36](https://user-images.githubusercontent.com/15362203/211701042-7202deae-5822-465f-ac60-cfb4c8108409.png)

Please do help, thank you!

**Comment by proprogramerX** [comment]
> Hello, pyccTrace.h should be in the subdirectory `CloudCompare/libs/qCC_db/include`. If it's not the case, are you sure how you cloned CloudComPy ? `git clone https://github.com/CloudCompare/CloudComPy.git --recurse-submodules` CloudCompare is seen here as a submodule of CloudComPy, there are some patches in CloudCompare needed to build CloudComPy with CloudCompare (pyccTrace.h is in one of these patches). The best way to synchronize the sources of all submodules is through the git submodules options. Let me know if this helps you solve this problem. Paul

Hi @prascle, thank you so much for the assistance, i managed to resolve the by re-cloning accordingly as you have advised.
However, I still cannot make the build files due to this error:
`/home/intern/test/CloudComPy/build/pyAPI/pyCC.cpp: In function ‘std::vector<QString>* exploreDB(ccHObject*, std::vector<QString>*, int)’:
/home/intern/test/CloudComPy/build/pyAPI/pyCC.cpp:410:23: error: aggregate ‘std::stringstream levstr’ has incomplete type and cannot be defined
  410 |     std::stringstream levstr;
      |                       ^~~~~~
/home/intern/test/CloudComPy/build/pyAPI/pyCC.cpp: In static member function ‘static bool ccContourLinesGenerator_::GenerateContourLines(ccRasterGrid*, const CCVector2d&, const ccContourLinesGenerator_::Parameters&, std::vector<ccPolyline*>&)’:
/home/intern/test/CloudComPy/build/pyAPI/pyCC.cpp:3059:59: error: ‘ccContourLinesGenerator’ has not been declared
 3059 |                                         poly->setMetaData(ccContourLinesGenerator::MetaKeySubIndex(), realCount);
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [pyAPI/CMakeFiles/PYCC_LIB.dir/build.make:76: pyAPI/CMakeFiles/PYCC_LIB.dir/pyCC.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2948: pyAPI/CMakeFiles/PYCC_LIB.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`
![Screenshot from 2023-01-11 10-04-36](https://user-images.githubusercontent.com/15362203/211967048-d862329f-3c90-44be-acb1-1d9779336ff2.png)

do you have any idea or suggestions on how I can resolve this? 
Thank you so much, I'm grateful for your support!

**Comment by proprogramerX** [comment]
> This is strange. For the first error, it seems that there is a missing system include in your case. `std::stringstream` must be solved by the chain of includes. Can you add `#include <sstream>` in `pyAPI/pyCC;cpp` (for instance in line 70) The second error is also strange, `ccContourLinesGenerator` must aslo be solved by the chain of includes. It seems that some sources are not correctly synchronised... Can you give me the result of the following commands in CloudComPy source directory ?
> 
> ```
> git status
> git submodule status --recursive 
> ```
> 
> You should get something like this for the submodule status:
> 
> ```
> 897e672520cc3c8e92d72a5e8612d56297b736ef CloudCompare (v2.10.1-1274-g897e6725)
> b978cd3d397c2c486fed66545d319b85b5376e79 CloudCompare/libs/qCC_db/extern/CCCoreLib (heads/master-34-gb978cd3)
> f28ea52517b65faf5bccfa2ec6f50e5156cf5f1c CloudCompare/plugins/core/IO/qE57IO/extern/libE57Format (v2.3.0)
> 9117bd784328d9ac40ffa1f9cf487633a8a715d7 CloudCompare/plugins/core/Standard/qCanupo/contrib/dlib (v19.21)
> f0f307917ecbfc0c6824ebf4a87e09b640a1ad8f CloudCompare/plugins/core/Standard/qColorimetricSegmenter (remotes/origin/cccorelib_syntax_update)
> 2fb734808a2b26534118cb80f3231f230faf7f5c CloudCompare/plugins/core/Standard/qJSonRPCPlugin (remotes/origin/HEAD)
> e95052c4f9a79b93248d28cbfa11e94e64dda2ad CloudCompare/plugins/core/Standard/qMPlane (remotes/origin/HEAD)
> 43a9c6e0a4a8710bb8455755803adb8cc1497d0f CloudCompare/plugins/core/Standard/qMasonry (deffce0-22-g43a9c6e)
> ec688f9d6fd2934486c04e8b450a5ac22f97bfe5 CloudCompare/plugins/core/Standard/qPoissonRecon/extern/PoissonRecon (V7.0-122-gec688f9)
> ```
> 
> Paul

Hi @prascle Thank you for your help, I've ran the commands and this is the result I've gotten:
`intern@intern-GE76-Raider-11UH:~/test/CloudComPy$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    CMakeLists.txt
	deleted:    CloudCompare
	deleted:    doc/BuildLinuxConda.md
	deleted:    doc/BuildLinuxCondaDocker.md
	deleted:    doc/BuildUbuntuNative.md
	deleted:    doc/BuildWindowsConda.md
	deleted:    doc/CMakeLists.txt
	deleted:    doc/ReleaseNotes.md
	deleted:    doc/UseDockerLinuxConda.md
	deleted:    doc/UseDockerLinuxCondaBinary.md
	deleted:    doc/UseLinuxCondaBinary.md
	deleted:    doc/UseWindowsCondaBinary.md
	deleted:    doc/prerequisitesVersions.md
	deleted:    doc/samples/CMakeLists.txt
	deleted:    doc/samples/histogramOnDistanceComputation.ipynb
	deleted:    pyAPI/CMakeLists.txt
	deleted:    pyAPI/PyScalarType.h
	deleted:    pyAPI/ccNumpyIncludes.h
	deleted:    pyAPI/initCC.cpp
	deleted:    pyAPI/initCC.h
	deleted:    pyAPI/optdefines.h.in
	deleted:    pyAPI/pyCC.cpp
	deleted:    pyAPI/pyCC.h
	deleted:    pybind11/CMakeLists.txt
	deleted:    pybind11/CSF/CMakeLists.txt
	deleted:    pybind11/CSF/CSFPy.cpp
	deleted:    pybind11/CSF/CSF_DocStrings.hpp
	deleted:    pybind11/CSF/__init__.py
	deleted:    pybind11/HPR/CMakeLists.txt
	deleted:    pybind11/HPR/HPRPy.cpp
	deleted:    pybind11/HPR/HPR_DocStrings.hpp
	deleted:    pybind11/HPR/__init__.py
	deleted:    pybind11/M3C2/CMakeLists.txt
	deleted:    pybind11/M3C2/M3C2Py.cpp
	deleted:    pybind11/M3C2/M3C2_DocStrings.hpp
	deleted:    pybind11/M3C2/__init__.py
	deleted:    pybind11/MeshBoolean/CMakeLists.txt
	deleted:    pybind11/MeshBoolean/MeshBooleanPy.cpp
	deleted:    pybind11/MeshBoolean/MeshBoolean_DocStrings.hpp
	deleted:    pybind11/MeshBoolean/__init__.py
	deleted:    pybind11/NeighbourhoodPy.cpp
	deleted:    pybind11/NeighbourhoodPy.hpp
	deleted:    pybind11/NeighbourhoodPy_DocStrings.hpp
	deleted:    pybind11/PCL/CMakeLists.txt
	deleted:    pybind11/PCL/PCLPy.cpp
	deleted:    pybind11/PCL/PCL_DocStrings.hpp
	deleted:    pybind11/PCL/__init__.py
	deleted:    pybind11/PCV/CMakeLists.txt
	deleted:    pybind11/PCV/PCVPy.cpp
	deleted:    pybind11/PCV/PCV_DocStrings.hpp
	deleted:    pybind11/PCV/__init__.py
	deleted:    pybind11/RANSAC_SD/CMakeLists.txt
	deleted:    pybind11/RANSAC_SD/RANSAC_SDPy.cpp
	deleted:    pybind11/RANSAC_SD/RANSAC_SD_DocStrings.hpp
	deleted:    pybind11/RANSAC_SD/__init__.py
	deleted:    pybind11/ScalarFieldPy.cpp
	deleted:    pybind11/ScalarFieldPy.hpp
	deleted:    pybind11/ScalarFieldPy_DocStrings.hpp
	deleted:    pybind11/__init__.py
	deleted:    pybind11/ccFacetPy.cpp
	deleted:    pybind11/ccFacetPy.hpp
	deleted:    pybind11/ccFacetPy_DocStrings.hpp
	deleted:    pybind11/ccGenericCloudPy.cpp
	deleted:    pybind11/ccGenericCloudPy.hpp
	deleted:    pybind11/ccGenericCloudPy_DocStrings.hpp
	deleted:    pybind11/ccMeshPy.cpp
	deleted:    pybind11/ccMeshPy.hpp
	deleted:    pybind11/ccMeshPy_DocStrings.hpp
	deleted:    pybind11/ccOctreePy.cpp
	deleted:    pybind11/ccOctreePy.hpp
	deleted:    pybind11/ccOctreePy_DocStrings.hpp
	deleted:    pybind11/ccPointCloudPy.cpp
	deleted:    pybind11/ccPointCloudPy.hpp
	deleted:    pybind11/ccPointCloudPy_DocStrings.hpp
	deleted:    pybind11/ccPolylinePy.cpp
	deleted:    pybind11/ccPolylinePy.hpp
	deleted:    pybind11/ccPolylinePy_DocStrings.hpp
	deleted:    pybind11/ccPrimitivesPy.cpp
	deleted:    pybind11/ccPrimitivesPy.hpp
	deleted:    pybind11/ccPrimitivesPy_DocStrings.hpp
	deleted:    pybind11/ccSensorPy.cpp
	deleted:    pybind11/ccSensorPy.hpp
	deleted:    pybind11/ccSensorPy_DocStrings.hpp
	deleted:    pybind11/cloudComPy.cpp
	deleted:    pybind11/cloudComPy.hpp
	deleted:    pybind11/cloudComPy_DocStrings.hpp
	deleted:    pybind11/cloudSamplingToolsPy.cpp
	deleted:    pybind11/cloudSamplingToolsPy.hpp
	deleted:    pybind11/cloudSamplingToolsPy_DocStrings.hpp
	deleted:    pybind11/colorsPy.cpp
	deleted:    pybind11/colorsPy.hpp
	deleted:    pybind11/colorsPy_DocStrings.hpp
	deleted:    pybind11/condaCloud.sh
	deleted:    pybind11/conversions.hpp
	deleted:    pybind11/converters.hpp
	deleted:    pybind11/distanceComputationToolsPy.cpp
	deleted:    pybind11/distanceComputationToolsPy.hpp
	deleted:    pybind11/distanceComputationToolsPy_DocStrings.hpp
	deleted:    pybind11/geometricalAnalysisToolsPy.cpp
	deleted:    pybind11/geometricalAnalysisToolsPy.hpp
	deleted:    pybind11/geometricalAnalysisToolsPy_DocStrings.hpp
	deleted:    pybind11/minimalBoundingBox.py
	deleted:    pybind11/registrationToolsPy.cpp
	deleted:    pybind11/registrationToolsPy.hpp
	deleted:    sphinxDoc/CMakeLists.txt
	deleted:    sphinxDoc/CSF.rst
	deleted:    sphinxDoc/DistanceComputationTools.rst
	deleted:    sphinxDoc/GeometricalAnalysisTools.rst
	deleted:    sphinxDoc/HPR.rst
	deleted:    sphinxDoc/M3C2.rst
	deleted:    sphinxDoc/MeshBoolean.rst
	deleted:    sphinxDoc/MinimalBoundingBox.rst
	deleted:    sphinxDoc/Neighbourhood.rst
	deleted:    sphinxDoc/PCL.rst
	deleted:    sphinxDoc/PCV.rst
	deleted:    sphinxDoc/RANSAC_SD.rst
	deleted:    sphinxDoc/ScalarField.rst
	deleted:    sphinxDoc/ccFacet.rst
	deleted:    sphinxDoc/ccMesh.rst
	deleted:    sphinxDoc/ccOctree.rst
	deleted:    sphinxDoc/ccPointCloud.rst
	deleted:    sphinxDoc/ccPolyline.rst
	deleted:    sphinxDoc/ccPrimitives.rst
	deleted:    sphinxDoc/ccSensor.rst
	deleted:    sphinxDoc/cloudComPy.rst
	deleted:    sphinxDoc/cloudSamplingTools.rst
	deleted:    sphinxDoc/colors.rst
	deleted:    sphinxDoc/conf.py.in
	deleted:    sphinxDoc/genSphinxDoc.sh.in
	deleted:    sphinxDoc/genSphinxDocConda.sh.in
	deleted:    sphinxDoc/genSphinxDocWindows.bat.in
	deleted:    sphinxDoc/index.rst
	deleted:    sphinxDoc/introduction.rst
	deleted:    sphinxDoc/license.rst
	deleted:    sphinxDoc/postInstall.cmake
	deleted:    sphinxDoc/tables.rst
	deleted:    sphinxDoc/userEntities.rst
	deleted:    sphinxDoc/userIntro.rst
	deleted:    sphinxDoc/userLoad.rst
	deleted:    sphinxDoc/userNumpy.rst
	deleted:    sphinxDoc/userSave.rst
	deleted:    sphinxDoc/userUseCases.rst
	deleted:    tests/CMakeLists.txt
	deleted:    tests/DartConfiguration.tcl.in
	deleted:    tests/DartTestfile.txt
	deleted:    tests/DartTestfile.win.txt
	deleted:    tests/envPyCC.bat
	deleted:    tests/envPyCC.sh
	deleted:    tests/execInstallTest.bat
	deleted:    tests/execInstallTest.sh
	deleted:    tests/execTest.bat.in
	deleted:    tests/execTest.sh.in
	deleted:    tests/gendata.py.in
	deleted:    tests/test001.py
	deleted:    tests/test002.py
	deleted:    tests/test003.py
	deleted:    tests/test004.py
	deleted:    tests/test005.py
	deleted:    tests/test006.py
	deleted:    tests/test007.py
	deleted:    tests/test008.py
	deleted:    tests/test009.py
	deleted:    tests/test010.py
	deleted:    tests/test011.py
	deleted:    tests/test012.py
	deleted:    tests/test013.py
	deleted:    tests/test014.py
	deleted:    tests/test015.py
	deleted:    tests/test016.py
	deleted:    tests/test017.py
	deleted:    tests/test018.py
	deleted:    tests/test019.py
	deleted:    tests/test020.py
	deleted:    tests/test021.py
	deleted:    tests/test022.py
	deleted:    tests/test023.py
	deleted:    tests/test024.py
	deleted:    tests/test025.py
	deleted:    tests/test026.py
	deleted:    tests/test027.py
	deleted:    tests/test028.py
	deleted:    tests/test029.py
	deleted:    tests/test030.py
	deleted:    tests/test031.py
	deleted:    tests/test032.py
	deleted:    tests/test033.py
	deleted:    tests/test034.py
	deleted:    tests/test035.py
	deleted:    tests/test036.py
	deleted:    tests/test037.py
	deleted:    tests/test038.py
	deleted:    tests/test039.py
	deleted:    tests/test040.py
	deleted:    tests/test041.py
	deleted:    tests/test042.py
	deleted:    tests/test043.py
	deleted:    tests/test044.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	CMakeCache.txt
	CMakeFiles/
	DartConfiguration.tcl
	build/

no changes added to commit (use "git add" and/or "git commit -a")
intern@intern-GE76-Raider-11UH:~/test/CloudComPy$ git submodule status --recursive 
-897e672520cc3c8e92d72a5e8612d56297b736ef CloudCompare
`
It seems like I'm missing many of the libraries in CloudCompare, i think ill try to re-clone everything?

**Comment by proprogramerX** [comment]
Update: I've managed to update my git submodules and i ran the status command again
```
intern@intern-GE76-Raider-11UH:~/test/CloudComPy/build$ git submodule status --recursive 
 897e672520cc3c8e92d72a5e8612d56297b736ef ../CloudCompare (v2.10.1-1274-g897e6725)
 b978cd3d397c2c486fed66545d319b85b5376e79 ../CloudCompare/libs/qCC_db/extern/CCCoreLib (b978cd3)
 f28ea52517b65faf5bccfa2ec6f50e5156cf5f1c ../CloudCompare/plugins/core/IO/qE57IO/extern/libE57Format (v2.3.0)
 9117bd784328d9ac40ffa1f9cf487633a8a715d7 ../CloudCompare/plugins/core/Standard/qCanupo/contrib/dlib (v19.21)
 f0f307917ecbfc0c6824ebf4a87e09b640a1ad8f ../CloudCompare/plugins/core/Standard/qColorimetricSegmenter (remotes/origin/cccorelib_syntax_update)
 2fb734808a2b26534118cb80f3231f230faf7f5c ../CloudCompare/plugins/core/Standard/qJSonRPCPlugin (heads/master)
 e95052c4f9a79b93248d28cbfa11e94e64dda2ad ../CloudCompare/plugins/core/Standard/qMPlane (heads/master)
 43a9c6e0a4a8710bb8455755803adb8cc1497d0f ../CloudCompare/plugins/core/Standard/qMasonry (deffce0-22-g43a9c6e)
 ec688f9d6fd2934486c04e8b450a5ac22f97bfe5 ../CloudCompare/plugins/core/Standard/qPoissonRecon/extern/PoissonRecon (V7.0-122-gec688f9)
```
However, I'm currently facing the following errors:

```
/home/intern/test/CloudComPy/build/pyAPI/pyCC.cpp: In static member function ‘static bool ccContourLinesGenerator_::GenerateContourLines(ccRasterGrid*, const CCVector2d&, const ccContourLinesGenerator_::Parameters&, std::vector<ccPolyline*>&)’:
/home/intern/test/CloudComPy/build/pyAPI/pyCC.cpp:3061:59: error: ‘ccContourLinesGenerator’ has not been declared
 3061 |                                         poly->setMetaData(ccContourLinesGenerator::MetaKeySubIndex(), realCount);
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [pyAPI/CMakeFiles/PYCC_LIB.dir/build.make:76: pyAPI/CMakeFiles/PYCC_LIB.dir/pyCC.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2948: pyAPI/CMakeFiles/PYCC_LIB.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

![Screenshot from 2023-01-16 15-53-19](https://user-images.githubusercontent.com/15362203/212625747-cb89ce4a-218e-4893-98e4-b4adbd52f47d.png)

Thank you Paul for your help!

**Comment by prascle** [comment]
Hello,
It seems that you are trying to build directly in the source directory, which is not a good idea with CMake.
I don't know if you are trying to build only with Ubuntu native packages, or if you are using the conda environment, the one I use to produce binaries for Linux and Windows.
If you are working with conda packages, you can try using my [script](https://github.com/CloudCompare/CloudComPy/blob/master/building/genCloudComPy_Conda310_Ubuntu2004.sh) after cloning the [CloudComPy repository](https://github.com/CloudCompare/CloudComPy.git) into a separate directory. You will have to adapt the paths in the script according to your configuration, as long as you define 3 separate directories for source, build and install. You may also need to disable plugins that require libraries not provided by Linux or Conda packaging (CORK, DRACO, FBX, LIBIGL, OPENCASCADE libraries required by CORK, DRACO, FBXSDK, LAS_FWF and STEP plugins).
If you try without Conda, only with Linux packages, you have to adapt the script with all necessary library paths (I did not list the minimal set of required Linux packages).
Paul

**Comment by proprogramerX** [comment]
Thanks @prascle for the advice.
I've tried to use your script however, I'm unsure of how to disable plugins in cmake, after extensive google searches, I've tried this in cmake:
```
    -DPLUGIN_OPENCASCADE=OFF \
    -DPLUGIN_CORK=OFF \
    -DPLUGIN_DRACO=OFF \
    -DPLUGIN_FBXSDK=OFF \
    -DPLUGIN_LAS_FWF=OFF \
    -DPLUGIN_STEP=OFF 
```
But to no avail, I still cannot disable those plugins and cmake:
```
[ 63%] Linking CXX static library libQPCL_PLUGIN_UTILS_LIB.a
[ 63%] Built target QPCL_PLUGIN_UTILS_LIB
[ 63%] Linking CXX static library libQPOISSON_RECON_LIB.a
[ 63%] Built target QPOISSON_RECON_LIB
[ 63%] Linking CXX shared library libQCANUPO_PLUGIN.so
[ 63%] Built target QCANUPO_PLUGIN
make: *** [Makefile:146: all] Error 2
bash: cd: /home/intern/projets/hydro95/prerequisites/install/Occ-740p3EDFp1/lib: No such file or directory

```
Sorry for my ignorance

**Comment by prascle** [comment]
If you take a look at the script, you will find the lines corresponding to the activation of the plugins:

```
-DPLUGIN_IO_QDRACO:BOOL="1" \
-DPLUGIN_IO_QFBX:BOOL="1" \
-DPLUGIN_IO_QLAS_FWF:BOOL="1" \
-DPLUGIN_IO_QSTEP:BOOL="1" \
-DPLUGIN_STANDARD_QCORK:BOOL="1" \

```
Replace the "1" by "0" in these five lines, that should be enough to deactivate the plugins. The lines corresponding to the CORK, DRACO, FBX, LIBIGL, OPENCASCADE libraries can be kept as they are, they will not be read.

Paul

**Comment by louisgag** [comment]
I also compiled CloudCompPy on Ubuntu 20.04 and ran into some issues.. including this one above (ccContourLinesGenerator) and solved it by adding an extra (perhaps unecessary) include and most importantly getting the latest pybind11 package from github and compiling/installing it (not the ubuntu-package) before compiling CloudComPy... It was a little confusing at firt that the pybind11 folder in CloudCompare is not pybind11 itself :wink: 

the tests fail but the python interface works and yields plausible results when I check after my new cloud in CloudCompare
