### ISSUE TITLE
ImportError: DLL load failed while importing _cloudComPy: The specified procedure could not be found.

### ISSUE THREAD

**Issue by proprogramerX** [CloudCompare/CloudComPy#85]
Hi Paul,
I've been trying to get CloudComPy running on my Windows Laptop, I installed the latest version of the CloudComPy binary file, CloudComPy310_20221122, and I followed the steps on provided on https://github.com/CloudCompare/CloudComPy/blob/master/doc/UseWindowsCondaBinary.md . However, when I run the envCloudComPy.bat file, I get this error:
![image](https://user-images.githubusercontent.com/15362203/213395377-cb2f4f28-d33b-4533-891a-b9fc0f0a7766.png)

and when I run ctest, all my tests fail:

![image](https://user-images.githubusercontent.com/15362203/213393731-72e31f92-e85b-46bf-87b7-93d98d21c016.png)

with this error recurring for all the failed tests in the error log:

![image](https://user-images.githubusercontent.com/15362203/213393666-95afebad-6cad-4f45-98a5-0152b7779ab6.png)

Thank you and I appreciate your help!

**Comment by prascle** [comment]
Hello,
I don't see anything wrong with what you have done, however, the _cloudComPy library (` .../CloudComPy310/CloudCompare/_cloudComPy.pyd`) is not loaded correctly, there is probably a missing library.
Can you install [Dependencies](https://github.com/lucasg/Dependencies) and run DependencyGui.exe from the Conda prompt, after setting the CloudComPy310 environment and the enCloudComPy.bat environment?
Open `_cloudComPy.pyd`. If something is missing, you'll find it.
When it's right, you get something like this:
![image](https://user-images.githubusercontent.com/63641539/213439347-6dbf46ea-c1f3-48d6-932f-0e0dcda6191f.png)
Let me know what's missing...
Paul

**Comment by proprogramerX** [comment]
Hi Paul, 
This is my output for the DependenciesGui.exe from the Conda prompt:
![image](https://user-images.githubusercontent.com/15362203/213598931-e8423ce6-a5dc-4dce-b593-d77762f9206d.png)

In comparison with yours, I can't seem to spot any differences.
Thank you for the support!

**Comment by prascle** [comment]
Hi, this is very strange. 
The error you have on CloudCompare is probably the same as for the `_cloudComPy.pyd` library: it seems that the `Qt5Concurrent` library is not found. When you expand the dependencies on `CCCoreLib.dll` in DependencyGui.exe, you should find something like 
`C:\users\user\anaconda3\envs\CloudComPy310\Library\bin\Qt5Concurrent_conda.dll` in the list. If the library is present and seems to be correctly loaded, I don't understand the error...
You can apply DependencyGui.exe on CloudCompare.exe to check if you detect a library problem. If you don't see an error and you get an error when running CloudCompare in the exact same environment as used for DependencyGui.exe, I don't understand...
Note: your Python is not the problem for the CloudCompare error, CloudCompare does not rely on Python. 
Paul

**Comment by mariohopfner** [comment]
I had the same problem with the "Entry point not found" error.

After some testing, I compared the installed conda packages and found, that there are quite some differences. All minor changes, but downgrading Qt did the trick for me.

I forced Qt back to version _5.15.4_ (as used by @prascle) by using
`conda install "qt=5.15.4`

Conda should automatically clear all dependencies and downgrade a few packages.
After the downgrade, CloudCompare was instantly runnable for me. And all tests (except 38) passed.

**Comment by prascle** [comment]
Thank you very much @mariohopfner for this information!
I reproduced the problem: Qt5.15.6 is incompatible with Qt 5.15.4! I naively thought that versions differing only by the third digit (patch number) are compatible as it is the case for Python.
I will correct this asap in the documentation...

**Comment by proprogramerX** [comment]
Thank you so much this solution worked for me! @mariohopfner
Thank you @prascle for the excellent support!

> I had the same problem with the "Entry point not found" error.
> 
> After some testing, I compared the installed conda packages and found, that there are quite some differences. All minor changes, but downgrading Qt did the trick for me.
> 
> I forced Qt back to version _5.15.4_ (as used by @prascle) by using `conda install "qt=5.15.4`
> 
> Conda should automatically clear all dependencies and downgrade a few packages. After the downgrade, CloudCompare was instantly runnable for me. And all tests (except 38) passed.
