### ISSUE TITLE
Segmentation Fault when deleting a cloud created by ccPointCloud

### ISSUE THREAD

**Issue by xiangtaoxu** [CloudCompare/CloudComPy#90]
Hi, 
[test_pointcloud.zip](https://github.com/CloudCompare/CloudComPy/files/10794944/test_pointcloud.zip)

I noticed this error. Please see attached for a script that reproduces the error. 

In my workflow, I often create temporary cloud from numpy array and I would like to release the memory at the end of a function.

**Comment by prascle** [comment]
Hi, 
I reproduced the error, I'm trying to debug it and fix it as soon as possible.
Thanks for this simple script, it's very helpful to isolate the bug!

Regards,
Paul
