### ISSUE TITLE
Time SF has been shifted to prevent a loss of accuracy

### ISSUE THREAD

**Issue by giplessis** [CloudCompare/CloudComPy#94]
Dear all, 
I'm using CloudComPy to work with LiDAR data having a scalar field describing the GPS time. 
When I use CloudCompare, I see that the "Time SF has been shifted to prevent a loss of accuracy". 
Is there a way to retrieve this shift in CloudComPy?
Best regards,

**Comment by prascle** [comment]
Hi,
I am not familiar with this type of data. There is probably no way to retrieve this offset value with the current version of CloudCompy, but if it is possible, I can try to implement a solution.  I found the corresponding code in CloudCompare, but it will be easier to test and analyze it with some data. Do you have an example file to reproduce this behavior?
Regards,
Paul

**Comment by giplessis** [comment]
Hi Paul,
Thanks a lot for your help. 
Please find attached a minimal cloud example integrating this scalar field with large value. 
Cheers, 
Gilles
[lidar_veg_cloud.zip](https://github.com/CloudCompare/CloudComPy/files/10874108/lidar_veg_cloud.zip)

**Comment by prascle** [comment]
Hello @giplessis 
I have implemented the function to retrieve the shift in CloudComPy. 
I hope it possible to use your sample file in my automated tests. If not, please let me know, I will have to find some other sample data.
Regards,
Paul
